server:
  port: 8761

security:
  basic:
    enabled: false
  ignored:
    - console/**
    - health

management:
  security:
    enabled: false

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
