server:
  port: 8761

security:
  basic:
    enabled: false
  ignored:
    - console/**
    - health

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false

