server:
  port: 8080

security:
  basic:
    enabled: false
  ignored:
    - console/**
    - health

spring:
  boot:
    admin:
      discovery:
        services: server-admin
management:
  security:
    enabled: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
